name: Generate Utile OS 26 ISO

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  gen-custom-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2
    
      - name: Build
        run: |
          docker run --privileged -v ${{ github.workspace }}:/workspace --platform linux/amd64 --name utile-build-container -w /workspace ubuntu:26.04 /bin/bash -c "
            set -exuo pipefail # Strict
            uname -m
            export DEBIAN_FRONTEND=noninteractive
            apt-get update && apt-get install -y live-build debootstrap squashfs-tools xorriso
            apt-get upgrade -y

            mkdir -p /workspace/build
            cd /workspace/build
            lb config --mode ubuntu --distribution resolute --architecture amd64 --archive-areas "main restricted universe multiverse"
            tar -czf live-build-config.tar.gz auto/ config/ local/
            chown -R $(id -u):$(id -g) /workspace/build
          "
    
      - name: List build directory
        run: |
          echo "Workspace: $GITHUB_WORKSPACE"
          ls -la $GITHUB_WORKSPACE || true
          ls -la $GITHUB_WORKSPACE/build || true

      - name: Upload Build Directory
        uses: actions/upload-artifact@v7
        with:
          name: live-build-config
          path: build/live-build-config.tar.gz
          if-no-files-found: error