name: Generate Utile OS 26 ISO

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  gen-custom-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Preseed snaps
        env:
          # If this was triggered by a tag (release), set to release. Otherwise, nightly will automatically be used.
          BUILD_TYPE: ${{ startsWith(github.ref, 'refs/tags/') && 'release' || '' }}
        run: |
          pnpm install
          node src/preseed-snaps.js
          node src/inject-disk-release.js
    
      - name: Build
        run: |
          cat > ${{ github.workspace }}/temp/docker-live-build.sh << 'EOF'
            set -exuo pipefail
            export DEBIAN_FRONTEND=noninteractive
            apt-get update && apt-get install -y live-build debootstrap squashfs-tools xorriso
            apt-get upgrade -y

            mkdir -p /workspace/build
            cd /workspace/build
            lb config \
            --mode ubuntu \
            --distribution resolute \
            --architecture amd64 \
            --archive-areas "main restricted universe multiverse" \
            --iso-application "Utile OS Live" \
            --iso-volume "Utile OS 26 amd64" \
            --iso-publisher 'Utile; https://utile-os-web.mailworker.workers.dev; proman4713@gmail.com'

            mkdir -p /workspace/build/config/archives
            cp -r /workspace/tooling/config/archives/* /workspace/build/config/archives/

            mkdir -p /workspace/build/config/hooks
            cp -r /workspace/tooling/config/hooks/* /workspace/build/config/hooks/
            chmod +x /workspace/build/config/hooks/*

            mkdir -p /workspace/build/config/package-lists
            cp -r /workspace/tooling/config/package-lists/* /workspace/build/config/package-lists/

            mkdir -p /workspace/build/config/includes.chroot
            cp -r /workspace/tooling/config/includes.chroot/* /workspace/build/config/includes.chroot/

            mkdir -p /workspace/build/config/includes.binary
            cp -r /workspace/tooling/config/includes.binary/* /workspace/build/config/includes.binary/

            mkdir -p /workspace/build/config/preseed
            cp -r /workspace/tooling/config/preseed/* /workspace/build/config/preseed/
            EOF

          docker run --privileged -v ${{ github.workspace }}:/workspace --platform linux/amd64 --name utile-build-container -w /workspace ubuntu:26.04 /bin/bash /workspace/temp/docker-live-build.sh
    
      - name: Compress Build Directory
        run: |
          set -euo pipefail # Strict

          echo "Workspace: $GITHUB_WORKSPACE"
          sudo chown -R $(id -u):$(id -g) $GITHUB_WORKSPACE/build
          tree $GITHUB_WORKSPACE/tooling/config || true
          tree $GITHUB_WORKSPACE/build || true

          tar -czvf live-build-config.tar.gz -C $GITHUB_WORKSPACE/build .

      - name: Upload Build Directory
        uses: actions/upload-artifact@v7
        with:
          name: live-build-config
          path: live-build-config.tar.gz
          if-no-files-found: error